name: Anatole Branch Portfolio
favicon: null
layout_spectrum: 0.25
typography_spectrum: 0.18265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
