name: Anatole Branch Portfolio
favicon: null
layout_spectrum: 0.1603416500147432
typography_spectrum: 0.18265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7106189322657883
  lightness: 0.45705068903043866
  saturation: 0.744063711958006
  rhythmicContrast: 0.33050852734595537
purpose: []
